services:
  s3-minio:
    build:
      context: .
      dockerfile: Dockerfile.minio
    container_name: s3-minio
    ports:
      - "9000:9000"
      - "9080:9080"
    env_file:
      - s3-minio.env
    environment:
      MINIO_BROWSER: "on"
      MINIO_SERVER_URL: "http://localhost:9000"
    command: server /data --console-address ":9080"
    volumes:
      - minio-data:/data
    networks:
      - back
    restart: unless-stopped
    
  server:
    build: ./server
    container_name: server
    env_file:
      - server_config.env
    depends_on:
      db:
        condition: service_healthy
      
    environment:
      PORT: 1488
      NODE_ENV: development

    ports:
      - "1488:1488"
    volumes:
      - ./server:/app
      # - nfs-data:/nfs/shared
      - ./server/node_modules:/app/node_modules
    networks:
      - back
    restart: unless-stopped

  db:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    env_file:
      - postgres.env
    ports:
      - "5434:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      # - ./initdb:/docker-entrypoint-initdb.d
      # - nfs-data:/nfs/shared
    networks:
      - back
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  back:
    name: back
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  db-data:
  minio-data:
  